include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, "**/*.g.dart"]
  errors:
    todo: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_relative_imports: true
    require_trailing_commas: true
    depend_on_referenced_packages: false